### ISSUE TITLE
Finish Centrality Section 

### ISSUE THREAD

**Issue by bbengfort** [foxbook/atap#1]
- [ ] run centrality metrics 
- [x] expand sections describing centrality

**Comment by bbengfort** [comment]
I've got centrality metrics running on lagoon right now -- so far betweenness has been running for 35 hours. It's hard to finish this section without the metrics being run, and I'm not sure what to do, other than to convert the networkx graph into a graph-tool binary format and run the metrics on it. 

@rebeccabilbro unfortunately, I don't think this section will be ready for today, we'll just have to go to preprint as it is. I'll add some notes in the text to clean it up a bit so it doesn't look so bad in print.

**Comment by rebeccabilbro** [comment]
@bbengfort no worries! Thanks for offering to clean up the ch8 text for the preprint -- and hopefully lagoon comes through with some interesting results!
