### ISSUE TITLE
Issue to download cooking_corpus

### ISSUE THREAD

**Issue by chloeskt** [foxbook/atap#100]
Need to put all recipes into a zip file and leave a dropbox link to this zip file. Otherwise, the file is too large to be download (dropbox seems to crash)

**Comment by furyhawk** [comment]
dropbox link is dead now

**Comment by bbengfort** [comment]
@chloeskt @furyhawk thank you so much for reading Applied Text Analysis with Python! Sorry that you were having trouble downloading the cooking corpus. See if you can download it here instead: [https://bit.ly/3cRCHn6](https://bit.ly/3cRCHn6).
