### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 

### ISSUE THREAD

**Issue by win32nipuh** [foxbook/atap#102]
I run the code with the data file:
https://github.com/foxbook/atap/tree/master/snippets/ch01

but receive the error
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1526: character maps to <undefined>
This file contain some of '. But it is Unicode. 

What is the reason? how to fix it? 
-------------------------------
SOLVED:
The solution is:
open(FPATH, 'r', encoding = 'utf-8')  #<----------------- add the encoding parameter

**Comment by bbengfort** [comment]
Gald you figured it out!
