### ISSUE TITLE
Models Tour

### ISSUE THREAD

**Issue by bbengfort** [foxbook/atap#4]
Write a section that does a "tour of model families" including:

- [ ] Naive Bayes 
- [ ] Maximum Entropy (LogisticRegression)
- [ ] SVMs
- [ ] Forests 
- [ ] Perceptrons, maybe also Neural Networks

**Comment by rebeccabilbro** [comment]
In chapter 4, we take a "use all the models" approach and look for the most performance. With chapter 5, we're clustering, looking for patterns. The model decides what constitutes a pattern, meaning that we have to understand a bit more about how the models work before we use them.
