### ISSUE TITLE
Standardize footnotes

### ISSUE THREAD

**Issue by rebeccabilbro** [foxbook/atap#51]
All footnotes should have a citation and a bitly link.

**Comment by bbengfort** [comment]
Not sure if this is too much work (hopefully it's just a find in project for `footnote`) -- but if we could make a spreadsheet of all footnotes and links, I could bit.ly-ify them and we would have tracking for folks who are typing in links from the book.

**Comment by ojedatony1616** [comment]
Footnotes have been collected into the following Google Sheet - https://docs.google.com/spreadsheets/d/1ZsbGEinnbUlefqV3mLZ_Y9ypsUhY2efQFJCJ-hnJyoY/edit?usp=sharing

**Comment by bbengfort** [comment]
URLs in CSV have been shortened and added as a new sheet in the Google Docs. 

Script here: https://gist.github.com/bbengfort/92b90dab880b87bb5dca24522111789e
