### ISSUE TITLE
Chatbot refactor

### ISSUE THREAD

**Issue by rebeccabilbro** [foxbook/atap#61]
Refactoring the chatbot framework to create a more cohesive story for the chapter.

Todos include:

 - [x] Refactor `Conversation` class to employ a mapping to keep track of `Dialogs`
 - [x] Debug `Greeting`
 - [ ] Add 'awaiting response' state to `Greeting`
 - [x] Update conversion functionality to be a `Dialog`
 - [x] Add math feature to conversion to extend current function
 - [x] Stub but do not implement history feature for conversion (will be described but not implemented in chapter text)
 - [x] Implement recommender as `Dialog`
 - [x] Stub but do not implement online version (will describe in text how upvoting would work to add dimension to data for model retraining)

**Comment by bbengfort** [comment]
Tried adding `awaiting response` - but it was a bit complex in code; let's maybe just add it to the text? E.g. currently the conversation:

```
=# Hello!
Hello, what is your name? (1.00)
=# My name is Ben.
Hello, Ben! (1.00)
```

works, but not:

```
=# hello
Hello, what is your name? (1.00)
=# Ben
I'm sorry, I didn't get that (0.00)
```

**Comment by bbengfort** [comment]
Am utilizing the `collections.deque` class to implement the history stub. This data structure has a maximum length that automatically truncates the last items in the list. By using the `appendleft` method, it operates as a most recent items queue:

```python
from collections import deque

history = deque(maxlen=5)

for i in range(10):
    history.appendleft(i)

print("most recent item: {}".format(history[0]))
print("items in history: {}".format(len(history)))
print("3 in history: {}".format(3 in history))
print("8 in history: {}".format(8 in history))
``` 

```
most recent item: 9
items in history: 5
3 in history: False
8 in history: True
```
