### ISSUE TITLE
Execution of CH3 Preprocess

### ISSUE THREAD

**Issue by cheidger** [foxbook/atap#76]
Hello,

Loving the book so far, but am having issues writing the code to execute the preprocess snippet in Ch2 in this repository. I have downloaded the the Baleen data set linked to this home page. 

Would it be possible to add the execution code for this snippet? 

Many thanks!
Chris

**Comment by bbengfort** [comment]
@cheidger glad to hear you're enjoying the book! I'm not sure exactly what you mean by execution code; does the following not work?

```python
from reader import HTMLCorpusReader
from preprocess import Preprocessor 

if __name__ == "__main__":
    corpus = HTMLCorpusReader("path/to/html/corpus") 
    preprocessor = Preprocessor(corpus, "path/to/pickled/corpus")
    preprocessor.transform() 
```

Make sure this script is in the `snippets/ch03` directory so that it can import from reader.py and preprocess.py.

**Comment by danielw2904** [comment]
Sorry for hijacking the thread but `preprocessor.transform()` doesn't work for me. However if I just do

`for fileid in preprocessor.fileids():
    preprocessor.process(fileid)`

it works. Any ideas what I am doing wrong?

**Comment by bbengfort** [comment]
@danielw2904 well, it could certainly be a bug in `preprocessor.transform()` - what error are you getting?

**Comment by danielw2904** [comment]
I am not getting an error at all it is simply not called. The transform function does not seem to be called at all. I added a print statement at the end of the for loop and it doesn't show either. 
My code looks as follows:

```
from preprocess import Preprocessor
from reader import HTMLCorpusReader

if __name__ == "__main__":
    corpus = HTMLCorpusReader('./data')
    preprocessor = Preprocessor(corpus, './pickled')
    preprocessor.transform()
``` 

I have `corpus` and `preprocessor` in my environment and can access them. Just transform doesn't do anything. 

``` def transform(self, fileids = None, categories = None):
        """
        Transform the wrapped corpus, writing out the segmented, tokenized,
        and part of speech tagged corpus as a pickle to the target directory.
        This method will also directly copy files that are in the corpus.root
        directory that are not matched by the corpus.fileids().
        """
        # Make the target directory if it doesn't already exist
        if not os.path.exists(self.target):
            os.makedirs(self.target)

        # Resolve the fileids to start processing
        for fileid in self.fileids(fileids, categories):
            yield self.process(fileid)
            print("processed") # DOES NOT PRINT
```

**Comment by rebeccabilbro** [comment]
Hi @danielw2904 and thank you for checking out our book! 

Can you please paste in an example filename from your corpus? 

My first thought is that you may need to update the regex pattern used by the corpus reader (which is then used by the preprocessor). The pattern we introduce in chapter 2 of the book, in the section "Reading an HTML Corpus", is 

```DOC_PATTERN = r'(?!\.)[a-z_\s]+/[a-f0-9]+\.json'```

which is meant to anticipate HTML documents stored as JSON files that match the above regular expression (essentially, files with a string of lowercase letters, followed by an underscore and a few more lowercase letters or numbers, and ending with '.json'). This will match documents that look like 'reviews_123.json' or 'books_abc.json' but not 'B.html' or 'discussion.html'. If your documents are stored with different naming conventions or in a different filetype, the regex pattern from the book will skip those documents when it looks in the folder, meaning the code may run but the documents won't be read in by the corpus reader or processed by the preprocessor.

**Comment by rebeccabilbro** [comment]
Oops, just saw your update @danielw2904 - yes, `preprocessor.transform()` is a generator, which is just writing to disk and not printing to the terminal; if you wanted to print out the processed document or filepath each time the processed pickle gets written, try doing it inside of `process()`:

```
    def process(self, fileid):
        """
        For a single file does the following preprocessing work:
            1. Checks the location on disk to make sure no errors occur.
            2. Gets all paragraphs for the given text.
            3. Segements the paragraphs with the sent_tokenizer
            4. Tokenizes the sentences with the wordpunct_tokenizer
            5. Tags the sentences using the default pos_tagger
            6. Writes the document as a pickle to the target location.
        This method is called multiple times from the transform runner.
        """
        # Compute the outpath to write the file to.
        target = self.abspath(fileid)
        parent = os.path.dirname(target)

        # Make sure the directory exists
        if not os.path.exists(parent):
            os.makedirs(parent)

        # Make sure that the parent is a directory and not a file
        if not os.path.isdir(parent):
            raise ValueError(
                "Please supply a directory to write preprocessed data to."
            )

        # Create a data structure for the pickle
        document = list(self.tokenize(fileid))

        print(document) # If you want to print out each document as it's processed

        # Open and serialize the pickle to disk
        with open(target, 'wb') as f:
            pickle.dump(document, f, pickle.HIGHEST_PROTOCOL)

        print(target) # If you want to print the filename of each processed, pickled doc

        # Clean up the document
        del document

        # Return the target fileid
        return target
```

**Comment by danielw2904** [comment]
I have adapted the pattern and the file IDs are stored correctly in the `preprocessor`. I still need the list comprehension to wrote to disk. The generator does not seem to do anything by itself. I am not very familiar with generators so maybe I am doing something wrong.

**Comment by dtilson** [comment]
Just to add that I had the same experience as  danielw2904 . . . and it also worked with the addition of the list comprehension.

**Comment by bbengfort** [comment]
@dtilson thanks for the note - because transform is yielding, you have to iterate over it in order to get it to execute, I've fixed the code as follows:

```python
    def transform(self, fileids=None, categories=None):
        """
        Transform the wrapped corpus, writing out the segmented, tokenized,
        and part of speech tagged corpus as a pickle to the target directory.
        This method will also directly copy files that are in the corpus.root
        directory that are not matched by the corpus.fileids().
        """
        # Make the target directory if it doesn't already exist
        if not os.path.exists(self.target):
            os.makedirs(self.target)

        # Resolve the fileids to start processing and return the list of 
        # target file ids to pass to downstream transformers. 
        return [
            self.process(fileid)
            for fileid in self.fileids(fileids, categories)
        ]
```

This change should be reflected in the latest commit.
