### ISSUE TITLE
Error in gensim_frequency_vectorize function in vectorization.py Chapter 4

### ISSUE THREAD

**Issue by dtilson** [foxbook/atap#79]
I think there are a couple of problems with the **gensim_frequency_vectorize** function in the   **vectorization.py** snippet for Chapter 4. 

1.  The **vectorize** function in the list comprehension should actually be the **tokenize** function instead (the **tokenize** function is in the same file).
2. The **doc2bow** method only accepts tokenized documents. The way the function is currently written results in it receiving untokenized ones

```
def gensim_frequency_vectorize(corpus):
    # The Gensim frequency vectorize method
    import gensim

    id2word = gensim.corpora.Dictionary([
        list(vectorize(doc)) for doc in corpus]
    )

    return [
        id2word.doc2bow(doc) for doc in corpus
    ]
```

The following alternative fixes both problems (following the example code on page 59 of the book) 
```
def gensim_frequency_vectorize(corpus):
    # The Gensim frequency vectorize method
    import gensim
    
    tokenized_corpus = [list(tokenize(doc)) for doc in corpus]
    id2word = gensim.corpora.Dictionary(tokenized_corpus)
        
    return  [id2word.doc2bow(doc) for doc in tokenized_corpus]
```

**Comment by bbengfort** [comment]
@dtilson thank you for opening this issue! I think you're right that the method should use `tokenize`, the `gensim.corpora.Dictionary` does the frequency counting. This is probably just a copy and paste error from [L28](https://github.com/foxbook/atap/blob/master/snippets/ch04/vectorization.py#L28); I'll make the update shortly.

**Comment by avialfont** [comment]
Hi,

As mentioned above, L56 should also use a tokenized version of corpus :

        id2word.doc2bow(doc) for doc in [list(vectorize(doc)) for doc in corpus],

this list being named tokenized_corpus in dtilson's comment (as in book's spirit).

Many thanks and best regard !

**Comment by ojedatony1616** [comment]
@avialfont Thanks for catching that. We'll look into this and correct shortly.
