### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by rebeccabilbro** [foxbook/atap#8]
write it

**Comment by rebeccabilbro** [comment]
@bbengfort - when you have a moment, can you send me the TFIDF script you mentioned?

**Comment by bbengfort** [comment]
Pushed it to Atlas = code/utils/keyterms.py 

run with: `python code/utils/keyterms.py -N 20 -o terms.txt` 

It might generate a little bit of junk but on my quick run through it, it seemed to generate a nice list of potential candidates for the glossary. You can also increase N to increase the number of terms per chapter it prints out.

**Comment by rebeccabilbro** [comment]
Perfect, thank you @bbengfort!

**Comment by rebeccabilbro** [comment]
Draft complete and pushed to atlas.
