### ISSUE TITLE
Chapter 10: ZIP file too large at Dropbox

### ISSUE THREAD

**Issue by karelin** [foxbook/atap#83]
When I try to download the cooking corpus from Dropbox, it produces an error message 'The zip file is too large'.

Perhaps, it is better to distribute the corpus as several smaller ZIP files?

**Comment by bbengfort** [comment]
Hi @karelin -- sorry it's taken us a while to respond, this message got buried in my GitHub notifications. We're not sure about splitting the corpus, but we're looking into storing it somewhere else that will allow the download. Ping us again if you don't hear from us in the next couple of weeks!

**Comment by ojedatony1616** [comment]
I've uploaded the corpus to S3, and it can be downloaded via the following URL: https://s3.amazonaws.com/ddl-data-lake/atap/cooking_corpus.tgz
