### ISSUE TITLE
Baleen Sample

### ISSUE THREAD

**Issue by DapangLiu** [foxbook/atap#85]
Hi!

I've just read your book and I'm wondering whether you can upload the sample code mentioned in your chapter two about composing our own corpus? I'm really curious about how to use Baleen to do that.

Thanks a lot! I love this book.

**Comment by bbengfort** [comment]
Hi @DapangLiu - thank you for reading our book and I'm so glad that you enjoyed it! 

Baleen is actually a pretty big library - you can find it here: https://github.com/DistrictDataLabs/baleen. Unfortunately, this version only supports Python 2 right now. Documentation about how to get started with Baleen is here: https://baleen-ingest.readthedocs.io/en/latest/. 

Good luck!
