### ISSUE TITLE
How to call ParallelPreprocessor in ch12 preprocess.py?

### ISSUE THREAD

**Issue by pauljohn32** [foxbook/atap#86]
I love this book, I'm able to get many of the examples to work correctly :)

In ch12 preprocess.py, I succeed with Preprocessor, but the ParallelProcessor does not seem to do any work.  It does create an output directory, but no files are created.   

Here's my effort to call that.  I commented out the one that works well, showing you my replacement, which creates a directory, but no files. But no error messages either.

```
    from reader import SqliteCorpusReader
    sqfn = '../../data/pitchfork/database.sqlite'
    corpus = SqliteCorpusReader(sqfn)
    # next works
    # transformer = Preprocessor(corpus, '../../data/pitchfork/review_corpus_proc')
    transformer = ParallelPreprocessor(corpus, target = '../../data/pitchfork/review_corpus_proc2')
    docs = transformer.transform()
    print(len(list(docs)))

**Comment by bbengfort** [comment]
Glad you're enjoying the book! 

I know multiprocessing can be a bit of a bear to work with, particularly as [multiprocessing is known to eat exceptions](https://stackoverflow.com/questions/6728236/exception-thrown-in-multiprocessing-pool-not-detected). 

Try adding the following:

```python
    def transform(self):
        """
        Create a pool using the multiprocessing library, passing in
        the number of cores available to set the desired number of
        processes.
        """
        # Make the target directory if it doesn't already exist
        if not os.path.exists(self.target):
            os.makedirs(self.target)

        # Reset the results
        self.results = []
        self.errors = []

        # Create a multiprocessing pool
        pool  = mp.Pool(processes=self.tasks)
        tasks = [
            pool.apply_async(self.process, (score_album_artist_text,), callback=self.on_result, error_callback=self.on_error)
            for score_album_artist_text in self.corpus.scores_albums_artists_texts()
        ]

        # Close the pool and join
        pool.close()
        pool.join()

        if len(self.errors) > 0:
            raise ValueError("{} errors occurred during transform".format(len(self.errors)))

        return self.results

    def self.on_error(self, e):
         self.errors.append(str(e))
```

**Comment by rebeccabilbro** [comment]
Hope the silence means that the suggestions helped out and you were able to move forward with your model training! I'll go ahead an archive this issue now in case another reader encounters similar issue in the future. Thanks again for checking out our book!
