### ISSUE TITLE
snark.py: f1_score, r2_score incorrect?

### ISSUE THREAD

**Issue by pauljohn32** [foxbook/atap#87]
snarky causes:

`ValueError: 'f1_score' is not a valid scoring value. Use sorted(sklearn.metrics.SCORERS.keys()) to get valid options.`

Changing to "f1" solves.  Same issue with code for continuous, "r2" needed, not "r2_score".

I don't see an evaluator called f1_score in any recent scikit.

**Comment by pauljohn32** [comment]
Sorry, changing to "f1" results in a different error. I've got sklearn 0.20.3, maybe there is a version issue.

End failure is

`ValueError: Target is multiclass but average='binary'. Please choose another average setting.`



`
In [2]: scores, delta = train_model(cpath, pipeline, continuous=False, saveto=mpath)
Iteration 1, loss = 0.87660830
Iteration 2, loss = 0.38449821
Iteration 3, loss = 0.06908916
Iteration 4, loss = 0.00960519
Iteration 5, loss = 0.00473178
Iteration 6, loss = 0.00386041
Iteration 7, loss = 0.00338882
Iteration 8, loss = 0.00306989
Iteration 9, loss = 0.00287480
Iteration 10, loss = 0.00276474
Iteration 11, loss = 0.00266341
Iteration 12, loss = 0.00255561
Iteration 13, loss = 0.00249819
Iteration 14, loss = 0.00241688
Iteration 15, loss = 0.00240989
Iteration 16, loss = 0.00229641
Iteration 17, loss = 0.00223010
Iteration 18, loss = 0.00216033
Iteration 19, loss = 0.00210243
Iteration 20, loss = 0.00205702
Iteration 21, loss = 0.00205167
Iteration 22, loss = 0.00193429
Iteration 23, loss = 0.00189662
Iteration 24, loss = 0.00186701
Iteration 25, loss = 0.00183344
Iteration 26, loss = 0.00175951
Iteration 27, loss = 0.00172533
Iteration 28, loss = 0.00168338
Iteration 29, loss = 0.00166739
Iteration 30, loss = 0.00163067
Iteration 31, loss = 0.00159168
Iteration 32, loss = 0.00155240
Iteration 33, loss = 0.00163203
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-fe6d78ca4bc4> in <module>
----> 1 import sys, codecs, os, ast;__pyfile = codecs.open('''/tmp/pyQ9hePK''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/pyQ9hePK''');__block = ast.parse(__code, '''/home/pauljohn/GIT/github/applied_text_analysis/snippets/ch12/snark.py''', mode='exec'); __block.body = (__block.body if not isinstance(__block.body[0], ast.If) else __block.body if not isinstance(__block.body[0].test, ast.Name) else __block.body if not __block.body[0].test.id == 'True' else __block.body[0].body) if sys.version_info[0] < 3 else (__block.body if not isinstance(__block.body[0], ast.If) else __block.body if not isinstance(__block.body[0].test, ast.NameConstant) else __block.body if not __block.body[0].test.value is True else __block.body[0].body);__last = __block.body[-1];__isexpr = isinstance(__last,ast.Expr);_ = __block.body.pop() if __isexpr else None;exec(compile(__block, '''/home/pauljohn/GIT/github/applied_text_analysis/snippets/ch12/snark.py''', mode='exec'));eval(compile(ast.Expression(__last.value), '''/home/pauljohn/GIT/github/applied_text_analysis/snippets/ch12/snark.py''', mode='eval')) if __isexpr else None

~/GIT/github/applied_text_analysis/snippets/ch12/snark.py in <module>
     82 
     83     print("Starting training...")
---> 84     scores, delta = train_model(cpath, pipeline, continuous=False, saveto=mpath)
     85 
     86     print("Training complete.")

~/GIT/github/applied_text_analysis/snippets/ch12/snark.py in wrapper(*args, **kwargs)
     12     def wrapper(*args, **kwargs):
     13         start = time.time()
---> 14         result = func(*args, **kwargs)
     15         return result, time.time() - start
     16     return wrapper

~/GIT/github/applied_text_analysis/snippets/ch12/snark.py in train_model(path, model, continuous, saveto, cv)
     51 
     52     # Compute cross validation scores
---> 53     scores = cross_val_score(model, X, y, cv=cv, scoring=scoring)
     54 
     55     # Fit the model on entire data set

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in cross_val_score(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, error_score)
    400                                 fit_params=fit_params,
    401                                 pre_dispatch=pre_dispatch,
--> 402                                 error_score=error_score)
    403     return cv_results['test_score']
    404 

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    238             return_times=True, return_estimator=return_estimator,
    239             error_score=error_score)
--> 240         for train, test in cv.split(X, y, groups))
    241 
    242     zipped_scores = list(zip(*scores))

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    915             # remaining jobs.
    916             self._iterating = False
--> 917             if self.dispatch_one_batch(iterator):
    918                 self._iterating = self._original_iterator is not None
    919 

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    757                 return False
    758             else:
--> 759                 self._dispatch(tasks)
    760                 return True
    761 

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    714         with self._lock:
    715             job_idx = len(self._jobs)
--> 716             job = self._backend.apply_async(batch, callback=cb)
    717             # A job can complete so quickly than its callback is
    718             # called before we get here, causing self._jobs to

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py in apply_async(self, func, callback)
    180     def apply_async(self, func, callback=None):
    181         """Schedule a func to be run"""
--> 182         result = ImmediateResult(func)
    183         if callback:
    184             callback(result)

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py in __init__(self, batch)
    547         # Don't delay the application, to avoid keeping the input
    548         # arguments in memory
--> 549         self.results = batch()
    550 
    551     def get(self):

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py in __call__(self)
    223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    224             return [func(*args, **kwargs)
--> 225                     for func, args, kwargs in self.items]
    226 
    227     def __len__(self):

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
    223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    224             return [func(*args, **kwargs)
--> 225                     for func, args, kwargs in self.items]
    226 
    227     def __len__(self):

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, return_n_test_samples, return_times, return_estimator, error_score)
    566         fit_time = time.time() - start_time
    567         # _score will return dict if is_multimetric is True
--> 568         test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
    569         score_time = time.time() - start_time - fit_time
    570         if return_train_score:

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _score(estimator, X_test, y_test, scorer, is_multimetric)
    603     """
    604     if is_multimetric:
--> 605         return _multimetric_score(estimator, X_test, y_test, scorer)
    606     else:
    607         if y_test is None:

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _multimetric_score(estimator, X_test, y_test, scorers)
    633             score = scorer(estimator, X_test)
    634         else:
--> 635             score = scorer(estimator, X_test, y_test)
    636 
    637         if hasattr(score, 'item'):

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/metrics/scorer.py in __call__(self, estimator, X, y_true, sample_weight)
     96         else:
     97             return self._sign * self._score_func(y_true, y_pred,
---> 98                                                  **self._kwargs)
     99 
    100 

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/metrics/classification.py in f1_score(y_true, y_pred, labels, pos_label, average, sample_weight)
    718     return fbeta_score(y_true, y_pred, 1, labels=labels,
    719                        pos_label=pos_label, average=average,
--> 720                        sample_weight=sample_weight)
    721 
    722 

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/metrics/classification.py in fbeta_score(y_true, y_pred, beta, labels, pos_label, average, sample_weight)
    832                                                  average=average,
    833                                                  warn_for=('f-score',),
--> 834                                                  sample_weight=sample_weight)
    835     return f
    836 

~/LinuxDownloads/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/metrics/classification.py in precision_recall_fscore_support(y_true, y_pred, beta, labels, pos_label, average, warn_for, sample_weight)
   1045         else:
   1046             raise ValueError("Target is %s but average='binary'. Please "
-> 1047                              "choose another average setting." % y_type)
   1048     elif pos_label not in (None, 1):
   1049         warnings.warn("Note that pos_label (set to %r) is ignored when "

ValueError: Target is multiclass but average='binary'. Please choose another average setting.
`

python 3.7 (Anaconda distribution)

I'm much more familiar with R, if you help me understand how to make a good Python bug report, I will do it.

**Comment by bbengfort** [comment]
@pauljohn32 thanks for the note - I think changing things to `"f1"` and `"r2"` is the right fix, but as you saw from the default `"f1"` this is also perilous depending on the target. Try `"f1_macro"` -- I think this should solve your issue!
