### ISSUE TITLE
Chap 5: Model Operationalization

### ISSUE THREAD

**Issue by SamehMannai** [foxbook/atap#92]
Hi,

While runing evaluate.py for prediction on new, incoming text in real time, by loading the estimator from the pickle object and using its predict() method, I get the following error:
ValueError: not enough values to unpack (expected 2, got 1)
I checked the input to the pipeline (text processed with preprocess() in evaluate.py) and it has the same format of the training data input. Any idea on how to fix this error?

Thanks in advance for any help!

**Comment by rebeccabilbro** [comment]
Hello again @SamehMannai &mdash; apologies but I may need more information to guess at what's triggering your error. Can you please paste in the full stacktrace?

**Comment by SamehMannai** [comment]
Hi Rebecca,
Thank you for the reply. Please find here below the error message when runing evaluate.py. I also have similar error with evaluate.py using the code in chapter 11.

C:\Documents\ch05>python evaluate.py
Pipeline(memory=None, steps=[('normalize', TextNormalizer(language=None)), ('vectorize', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',  dtype=<class 'numpy.float64'>, encoding='utf-8', input='content', lowercase=False, max_df=1.0, max_features=None, min_df=1,
ngram_range=(1,...penalty='l2', random_state=None, solver='warn', tol=0.0001, verbose=0, warm_start=False))])

[('Last', 'JJ'), ('summer', 'NN'), (',', ','), ('two', 'CD'), ('defensemen', 'NNS'), ('from', 'IN'), ('opposing', 'VBG'), ('conferences', 'NNS'), ('with', 'IN'), ('distinct', 'JJ'), ('styles', 'NNS'), ('of', 'IN'), ('play', 'NN'), ('and', 'CC'), ('contrasting', 'VBG'), ('personalities', 'NNS'), ('were', 'VBD'), ('forever', 'RB'), ('placed', 'VBN'), ('in', 'IN'), ('the', 'DT'), ('same', 'JJ'), ('breath', 'NN'), (',', ','), ('their', 'PRP$'), ('destinies', 'NNS'), ('intertwined', 'VBN'), ('by', 'IN'), ('a', 'DT'), ('trade', 'NN'), ('.', '.')]

Traceback (most recent call last):
  File "evaluate.py", line 47, in <module>
    print(sgd.predict(doc[0][0]))
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 118, in <lambda>   out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 331, in predict
    Xt = transform.transform(Xt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 1631, in transform
    X = super(TfidfVectorizer, self).transform(raw_documents)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 1086, in transform
    _, X = self._count_vocab(raw_documents, fixed_vocab=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 940, in _count_vocab
    for doc in raw_documents:
  File "C:\Documents\ch05\build.py", line 63, in transform
    yield self.normalize(document[0])
  File "C:\Documents\ch05\build.py", line 42, in normalize
    for paragraph in document
  File "C:\Documents\ch05\build.py", line 44, in <listcomp>
    for (token, tag) in sentence
ValueError: not enough values to unpack (expected 2, got 1)


Same error with chapter 11:

Traceback (most recent call last):
  File "evaluate.py", line 48, in <module>
    model2.predict(doc[0][0])
  File "C:\Anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 118, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 331, in predict
    Xt = transform.transform(Xt)
  File "C:\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 1631, in transform
    X = super(TfidfVectorizer, self).transform(raw_documents)
  File "C:\Users\sameh\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 1086, in transform
    _, X = self._count_vocab(raw_documents, fixed_vocab=True)
  File "C:\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 940, in _count_vocab
    for doc in raw_documents:
  File "C:\Documents\ch11\transformers.py", line 49, in transform
    yield self.normalize(document[0])
  File "C:\Documents\ch11\transformers.py", line 28, in normalize
    for paragraph in document
  File "C:\Documents\ch11\transformers.py", line 30, in <listcomp>
    for (token, tag) in sentence
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by rebeccabilbro** [comment]
Hi @SamehMannai &mdash; have you already performed all the corpus preprocessing steps from chapter 3 (which is summarized in the image below)? 

![image](https://user-images.githubusercontent.com/8760385/65079365-fdd80980-d96c-11e9-899f-de8f02edc152.png)

If you've followed those steps, your `tagged_corpus` will be a list of documents, composed of lists of paragraphs, which are lists of sentences, where a sentence is a list of (token, tag) tuples. My hypothesis is that you are getting this error because you haven't performed those steps or because your documents have a different structure (e.g. no paragraphs). 

Hope this helps!

**Comment by SamehMannai** [comment]
Hi Rebecca,
Thanks for the answer.
Yes, I performed all the corpus preprocessing steps then trained and built the Machine learning model that I wanted to use to predict the category of a new piece of text.
However, the processing of this new text is done with the preprocess() function defined in "evaluate.py" and its input is also lists of paragraphs, which are lists of sentences, where a sentence is a list of (token, tag) tuples. 

def preprocess(text):
    return [
        [
            list(nltk.pos_tag(nltk.word_tokenize(sent)))
            for sent in nltk.sent_tokenize(para)
        ] for para in text.split("\n\n")
    ]
doc = preprocess("""
Last summer, two defensemen from opposing conferences with distinct styles of play and contrasting personalities were forever placed in the same breath, their destinies intertwined by a trade.

The Nashville Predators sent Shea Weber, their cornerstone, to the Montreal Canadiens for P. K. Subban, who had become tremendously popular in Montreal and throughout the league. Subban, 27, won a Norris Trophy as the league’s top defenseman in 2013. Weber, 31, had been a three-time finalist for the award.
""")

**Comment by rebeccabilbro** [comment]
Hi again @SamehMannai &mdash; the issue appears to be that you are passing in only a single document to a pipeline that expects a list of document lists. Try passing in `[[doc]]` instead of `doc`.

**Comment by SamehMannai** [comment]
Hi Rebecca,
Thank you very much. It works.
