### ISSUE TITLE
Chapter 4: custom Gensim vectorization transformer

### ISSUE THREAD

**Issue by j-n-t** [foxbook/atap#93]
Hi,

Thank you for this great book. It has been a very interesting (and challenging!) read for the past few weeks, but I'm facing some issues with the code snippets.

In this particular case, should we be using `if os.path.exists(self.path):`? When `path=None` this raises an error: `TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`. Couldn't we use something like `if not self.path == None:` or something similar?

As for the transform method, should we be using a generator? When used directly, this poses no problem because we can always consume the generator with list() or something similar. However, isn't this a problem when used in a pipeline? Shouldn't we have something like:

```python
return [
    sparse2full(self.id2word.doc2bow(document), len(self.id2word)) 
    for document in documents
]
```

Thanks!
João

**Comment by j-n-t** [comment]
Thank you for your explanations, Rebecca.

Just to make sure I fully understand this: in that particular case you mention from chapter 6, since we are immediately consuming the generator, in practice there is no difference between doing it that way or just use a "regular" iterator, right?

Thanks!

**Comment by rebeccabilbro** [comment]
Yep, another design choice, which we'll leave up to you as you’ll have to adapt your code for your specific corpus and the input required by your particular downstream estimators! Best of luck and thanks again for checking out our book!
