### ISSUE TITLE
a few reproducible error in chapter.5

### ISSUE THREAD

**Issue by su-park** [foxbook/atap#94]
1. When model fits using GaussianNB input data 'X' needs to be dense.

  - I didn't inspect it further but got 'csr' error. 

2. In 'score_models' function, model.named_steps didn't work properly for me

  - so I recode it like as follows;

```python
def score_models(models, loader):
    for model in models:
        idx = len(model.steps)
        name = model.steps[idx-1][1].__class__.__name__
        if 'reduction' in model.steps[idx-2][0]:
            name += " (TruncatedSVD)"
```

**Comment by bbengfort** [comment]
Hi @su-park - thank you for the note, I'm glad that you figured it out!
